### ISSUE TITLE
Compositor window size

### ISSUE THREAD

**Issue by Hacker1245** [MyrikLD/LinusTrinus#10]
The current compositor size is too small when using a 1080p screen. Is there a way to either treat the phone as a second X server or a monitor? If I up the compositor window size to 1920x1080 I can't control the game because the window is hidden behind the compositor.

**Comment by MyrikLD** [comment]
This is a problem which I have not yet found a solution. Of course, I can stretch the window to full screen, but I do not consider this a solution. The correct way is to render the frame and send it to the program without a window, but so far I have not enough knowledge.

**Comment by MyrikLD** [comment]
Check my latest commit.
