### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Aang23** [MyrikLD/LinusTrinus#2]
Great project ! You're the only one who got this working ! But i'm unable to use it...

Here is the error :

alan@Ryzen-7:/usr/home/alan/Downloads/LinusTrinus-master/samples$ sudo bash make.sh 
[sudo] password for alan: 
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Compilation set for 64bits architectures.
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Found GLEW: /usr/include (Required is at least version "1.11") 
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/home/alan/Downloads/LinusTrinus-master/samples
Scanning dependencies of target driver_sample_autogen
[ 20%] Automatic MOC and UIC for target driver_sample
[ 20%] Built target driver_sample_autogen
Scanning dependencies of target driver_sample
[ 40%] Building CXX object driver_sample/CMakeFiles/driver_sample.dir/driver_sample.cpp.o
[ 80%] Building CXX object driver_sample/CMakeFiles/driver_sample.dir/driverlog.cpp.o
[ 80%] Building CXX object driver_sample/CMakeFiles/driver_sample.dir/driver_sample_autogen/mocs_compilation.cpp.o
/usr/home/alan/Downloads/LinusTrinus-master/samples/driver_sample/driver_sample.cpp:3:10: fatal error: openvr_driver.h: No such file or directory
 #include <openvr_driver.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
driver_sample/CMakeFiles/driver_sample.dir/build.make:86: recipe for target 'driver_sample/CMakeFiles/driver_sample.dir/driver_sample.cpp.o' failed
make[2]: *** [driver_sample/CMakeFiles/driver_sample.dir/driver_sample.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /usr/home/alan/Downloads/LinusTrinus-master/samples/driver_sample/driverlog.cpp:3:0:
/usr/home/alan/Downloads/LinusTrinus-master/samples/driver_sample/driverlog.h:9:10: fatal error: openvr_driver.h: No such file or directory
 #include <openvr_driver.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
driver_sample/CMakeFiles/driver_sample.dir/build.make:62: recipe for target 'driver_sample/CMakeFiles/driver_sample.dir/driverlog.cpp.o' failed
make[2]: *** [driver_sample/CMakeFiles/driver_sample.dir/driverlog.cpp.o] Error 1
CMakeFiles/Makefile2:86: recipe for target 'driver_sample/CMakeFiles/driver_sample.dir/all' failed
make[1]: *** [driver_sample/CMakeFiles/driver_sample.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
mkdir: cannot create directory ‘/home/alan/.steam/steam/steamapps/common/SteamVR/drivers/sample/bin/linux64’: No such file or directory
rm: cannot remove '/home/alan/.steam/steam/logs/*': No such file or directory

**Comment by timoteo7** [comment]
`/driver_sample.dir/driver_sample.cpp`
is trying to open `openvr_driver.h` and 
> No such file or directory

Download in the SDK of Valve:
[github.com/ValveSoftware/openvr/blob/master/headers](https://github.com/ValveSoftware/openvr/blob/master/headers/openvr_driver.h)

**Comment by Aang23** [comment]
Thanks, successfully fixed. Now the idea is to allow this to be recognised as a SteamVR headset...

**Comment by poVoq** [comment]
@Aang23 Did you manage to get this to run after all?

**Comment by qrkourier** [comment]
It still doesn't build after linking in openvr_driver.h.

```
~/Downloads/LinusTrinus/samples master*
❯ ls -l openvr_driver.h 
lrwxrwxrwx 1 kbingham kbingham   55 Aug 18 14:29 openvr_driver.h -> /home/kbingham/Downloads/openvr/headers/openvr_driver.h

~/Downloads/LinusTrinus/samples master*
❯ bash -eux make.sh
+ STEAM_PATH=/home/kbingham/.steam/steam
+ STEAMVR_PATH=/home/kbingham/.steam/steam/steamapps/common/SteamVR
+ (( 1<<32 ))
+ ARCH_TARGET=linux64
+ cmake . -DCMAKE_PREFIX_PATH=/opt/Qt/5.6/gcc_64/lib/cmake -DCMAKE_BUILD_TYPE=Release
-- Compilation set for 64bits architectures.
CMake Warning (dev) at /usr/share/cmake-3.13/Modules/FindOpenGL.cmake:270 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  CMakeLists.txt:105 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/kbingham/Downloads/LinusTrinus/samples
+ make -j4
[ 20%] Automatic MOC and UIC for target driver_sample
[ 20%] Built target driver_sample_autogen
[ 40%] Building CXX object driver_sample/CMakeFiles/driver_sample.dir/driverlog.cpp.o
[ 60%] Building CXX object driver_sample/CMakeFiles/driver_sample.dir/driver_sample.cpp.o
/home/kbingham/Downloads/LinusTrinus/samples/driver_sample/driver_sample.cpp: In function ‘void WatchdogThreadFunction()’:
/home/kbingham/Downloads/LinusTrinus/samples/driver_sample/driver_sample.cpp:137:54: error: no matching function for call to ‘vr::IVRWatchdogHost::WatchdogWakeUp()’                                                                                         
                 vr::VRWatchdogHost()->WatchdogWakeUp();
                                                      ^
In file included from /home/kbingham/Downloads/LinusTrinus/samples/driver_sample/driver_sample.cpp:3:
/home/kbingham/Downloads/LinusTrinus/samples/./openvr_driver.h:3429:15: note: candidate: ‘virtual void vr::IVRWatchdogHost::WatchdogWakeUp(vr::ETrackedDeviceClass)’                                                                                         
  virtual void WatchdogWakeUp( vr::ETrackedDeviceClass eDeviceClass ) = 0;
               ^~~~~~~~~~~~~~
/home/kbingham/Downloads/LinusTrinus/samples/./openvr_driver.h:3429:15: note:   candidate expects 1 argument, 0 provided
make[2]: *** [driver_sample/CMakeFiles/driver_sample.dir/build.make:76: driver_sample/CMakeFiles/driver_sample.dir/driver_sample.cpp.o] Error 1                                                                                                              
make[1]: *** [CMakeFiles/Makefile2:92: driver_sample/CMakeFiles/driver_sample.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by qrkourier** [comment]
```❯ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.04
DISTRIB_CODENAME=disco
DISTRIB_DESCRIPTION="Pop!_OS 19.04"
```

**Comment by Aang23** [comment]
@poVoq Sorry for the *very* late answer.
I got it to run and connect to my device, but it wasn't actually recognized in any OpenVR app. 
Probably gonna try again soon, but on Fedora 30 this time.

**Comment by calm0815** [comment]
https://github.com/MyrikLD/LinusTrinus/issues/2#issuecomment-522344709

I got same error.
Did you solve it ?
