### ISSUE TITLE
Connecting to SteamVR makes motherboard beeper go off

### ISSUE THREAD

**Issue by Flynn-Mandrake** [MyrikLD/LinusTrinus#23]
See title... Pairing the app with the server works just fine, and SteamVR seems to work fine too (save for some other issues that don't seem to be related to Trinus), but once I start SteamVR LinusTrinus displays the message 
`INFO:frame_generator.xwd_fg:Found compositor window id: 0x4e00008`
and my PC starts beeping like it just got stabbed.

**Comment by Corallus-Caninus** [comment]
https://github.com/MyrikLD/LinusTrinus/pull/24/commits/ed2386712ab7fba30877130c52949587243af715

This should fix it.

**Comment by Flynn-Mandrake** [comment]
That fixed it, thank you!
