### ISSUE TITLE
Does this still work with current Trinus?

### ISSUE THREAD

**Issue by Cybolic** [MyrikLD/LinusTrinus#3]
I've tried running this project as is with no luck (`python ./main.py`); I've also tried adding my local IP manually in `Discover.py` as well as changing the port from 7777 to 18086 but both Trinus and LinusTrinus stay waiting.

In short, does this project still work with current versions of Trinus or am I doing something wrong?

**Comment by MyrikLD** [comment]
Hello. 
I apologize, but at the moment I stop the development of this project (it was not possible to find like-minded people)

**Comment by poVoq** [comment]
https://github.com/JackD83/ALVR/issues/23

**Comment by Ghostbird** [comment]
It works with the current Trinus.

However I haven't managed to get SteamVR to recognise the software.

**Comment by Gamerstone** [comment]
I managed to make steam work but I can't get it in full screen I think that may be caused by my beta steam

**Comment by MyrikLD** [comment]
Steam already have example for virtual output device. But example for this api written only for windows and it too hard to understand, how to use it. It is reason, because I stop develop of this repo.
