### ISSUE TITLE
How do I install the SteamVR SDK to continue?

### ISSUE THREAD

**Issue by ichigo198777** [MyrikLD/LinusTrinus#49]
I followed each of the instructions. However when I arrive at the Compile and install driver step when [./make.sh]  is run it give a fatal error code of:

```
CMake Error at CMakeLists.txt:62 (message):
  OPENVRPATHS-NOTFOUND Please install SteamVR SDK to continue..
```

I don't know whats causing this however when I looked through the source code it references this to the error

```
# Check that the steamVR SDK is installed 
# (needed to prevent a segfault in OpenVR).
if(CMAKE_HOST_UNIX)
  find_file(OPENVRPATHS openvrpaths.vrpath PATHS $ENV{HOME}/.config/openvr "$ENV{HOME}/Library/Application Support/OpenVR/.openvr")
  if(${OPENVRPATHS} MATCHES OPENVRPATHS-NOTFOUND)
    message(FATAL_ERROR "${OPENVRPATHS} Please install SteamVR SDK to continue..")
  endif()
endif()
```

I use arch Linux with a gnome desktop and have Steam Vr installed What's causing this error and how do I fix it.

**Comment by zozonteq** [comment]
Same issue.
As far as I know at the moment the .config/openvr path is wrong.
The build succeeded after modifying CMakeLists.txt as follows.
```CMAKE
# Check that the steamVR SDK is installed
# (needed to prevent a segfault in OpenVR).
if(CMAKE_HOST_UNIX)
  find_file(OPENVRPATHS openvrpaths.vrpath PATHS $ENV{HOME}/.var/app/com.valvesoftware.Steam/.config/openvr/ "$ENV{HOME}/Library/Application Support/OpenVR/.openvr")
  if(${OPENVRPATHS} MATCHES OPENVRPATHS-NOTFOUND)
    message(FATAL_ERROR "${OPENVRPATHS} Please install SteamVR SDK to continue..")
  endif()
endif()
```
My enviroment.
```
OS:Endeavour
Steam:Flatpak
```

**Comment by ichigo198777** [comment]
That fixed the issue with The steam Vr open paths however it failed after it tryed to build the driver

`cp: cannot create directory '/home/active-user/.steam/steam/steamapps/common/SteamVR/drivers/': No such file or directory`
`mkdir: cannot create directory ‘/home/active-user/.steam/steam/steamapps/common/SteamVR/drivers/linus_trinus/bin/’: No such file or directory`
`cp: cannot create directory '/home/active-user/.steam/steam/steamapps/common/SteamVR/drivers/linus_trinus/bin/': No such file or directory
`
if it helps my steam Vr directory is located at
`/home/active-user/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/SteamVR`

**Comment by ichigo198777** [comment]
EDIT: managed to compile it changed the directory in make.sh to:
`STEAM_PATH=~/.var/app/com.valvesoftware.Steam`
`STEAMVR_PATH=$STEAM_PATH/.local/share/Steam/steamapps/common/SteamVR`

**Comment by zozonteq** [comment]
But I have another issue that video streamimg does not work.
How about you?
