### ISSUE TITLE
ALVR client support?

### ISSUE THREAD

**Issue by poVoq** [MyrikLD/LinusTrinus#9]
Not sure how similar the steaming protocol is, but there appears to be an open source system for GearVR/OcculusGo/Occulus Quest that only has a windows backend:

https://github.com/JackD83/ALVRClient
https://github.com/polygraphene/ALVRClient

Or maybe this app cloud be adapted to be a Trinus independent CardboardVR client to work with this?

Thanks for looking into it :)

**Comment by MyrikLD** [comment]
I cant run this program on my Xiaomi, so wait until i buy oculus quest :)
